bookers2/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users
  root to: 'homes#top'
  get "/home/about" =>"homes#about"

  get 'search' => 'searches#search'

  resources :books  do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end

  resources :users, only: [:index, :show, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end



end

bookers2/app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user

  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }

  def self.search(search, word)
   if search == "forward_match"
     @book = Book.where("title LIKE?","#{word}%")
   elsif search == "backward_match"
     @book = Book.where("title LIKE?","%#{word}")
   elsif search == "perfect_match"
     @book = Book.where(title:"#{word}")
   elsif search == "partial_match"
     @book = Book.where("title LIKE?","%#{word}%")
   else
     @book = Book.all
   end
  end

end

bookers2/app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :screen_book, only: [:edit, :update]

    def index
      @books = Book.all
      @book = Book.new
      @user = current_user
    end

    def show
      @book = Book.find(params[:id])
      @book_new = Book.new
      @user = @book.user
      @book_comment = BookComment.new
    end

    def new
      @book = Book.new
    end

    def create
      @book = Book.new(book_params)
      @book.user_id = current_user.id
     if @book.save
       redirect_to book_path(@book),notice: 'You have created book successfully.'
     else
       @user = current_user
       @books = Book.all
       render :index
     end
    end

    def edit
      @book = Book.find(params[:id])
    end

    def update
      @book = Book.find(params[:id])
      if @book.update(book_params)
        redirect_to book_path(@book), notice: 'You have updated book successfully.'
      else
        render :edit
      end
    end

    def destroy
      @book = Book.find(params[:id])
      @book.destroy
      redirect_to books_path
    end

    private
  def screen_book
    @book = Book.find(params[:id])
   if current_user.id != @book.user.id
     redirect_to books_path
   end
  end
    def book_params
      params.require(:book).permit(:title, :body)
    end

end

bookers2/app/helpers/books_helper.rb
module BooksHelper
end

bookers2/app/views/books/_sidebar.html.erb
 <div class="col-md-3">
      <h2>User info</h2>
      <%= attachment_image_tag user, :profile_image,  format: 'jpeg', fallback: "no_image.jpg", size: "60x60" %>
      <table class="table">
        <tr>
          <th>name</th>
          <th><%= user.name %></th>
        </tr>
        <tr>
          <th>introduction</th>
          <th><%= user.introduction %></th>
        </tr>
        <tr>
          <th>follows</th>
          <th>
            <%= link_to user_followings_path(@user) do %>
             <%= user.followings.count %>
            <% end %>
          </th>
        </tr>
        <tr>
          <th>followers</th>
          <th>
            <%= link_to user_followers_path(@user) do %>
             <%= user.followers.count %>
            <% end %>
          </th>
        </tr>
      </table>
      <div class="row">
          <% if user == current_user %>
            <%= link_to edit_user_path(@user), class: 'btn btn-outline-secondary btn-block' do %>
              <span class="fas fa-user-cog"></span>
            <% end %>
          <% else %>
            <% if current_user.following?(user) %>
              <%= link_to 'フォロー外す', user_relationships_path(user.id), method: :delete, class: 'btn btn-info' %>
            <% else %>
              <%= link_to 'フォローする', user_relationships_path(user.id), method: :post, class: 'btn btn-success' %>
            <% end %>
          <% end %>
      </div>
      <h2 class="mt-3">New book</h2>
      <%= form_with model: book, local:true do |f| %>
       <div class="form-group">
         <label>Title</label>
         <br><%= f.text_field :title, class: 'form-control' %></br>
       </div>
       <div class="form-group">
         <label>Opinion</label>
         <br><%= f.text_area :body, class: 'form-control' %></br>
       </div>
       <div class="form-group">
         <%= f.submit 'Create Book', class: 'btn btn-success' %>
       </div>
      <% end %>
   </div>

bookers2/app/views/books/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h1>Editing Book</h1>
       <% if @book.errors.any? %>
         <div class="EM">
          <%= @book.errors.count %>errors prohibited this obj from being saved:
          <% @book.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </div>
      <% end %>
      <%= form_with model:@book,  local:true do |f| %>
        <div class="form-group">
          <label>Title</label>
          <br><%= f.text_field :title, class: "form-control"%></br>
        </div>
        <div class="form-group">
          <label>Opinion</label>
          <br><%= f.text_area :body, class: "form-control"%></br>
        </div>
        <div class="form-group">
          <%= f.submit "Update Book", class: 'btn btn-success' %>
        </div>
      <% end %>
      <div>
        <span><%= link_to 'Show', "/books/#{@book.id}" %></span> |  <span><%= link_to 'Back', "/books" %></span>
      </div>
    </div>
  </div>
</div>

bookers2/app/views/books/index.html.erb
<div class="container px-5 px-sm-0">
  <% if @book.errors.any? %>
   <div class="EM">
      <%= @book.errors.count %>errors prohibited this obj from being saved:
       <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
       <% end %>
   </div>
  <% end %>
  <div class="row">
   <%= render 'books/sidebar', book: @book, user: @user %>
   <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th></th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
           <% @books.each do |book| %>
           <tr>

             <td>
               <%= link_to user_path(book.user.id) do %>
                 <%= attachment_image_tag book.user, :profile_image,  fallback: "no_image.jpg", class:"mt-3 rounded-circle", size: "40x40" %>
               <% end %>
             </td>
             <td>
               <%= link_to book_path(book.id) do %>
                 <%= book.title %>
               <% end %>
             </td>
             <td><%= book.body %></td>
             <td id="book_<%= book.id %>">
               <%= render 'favorites/list', book: book %>
             </td>
             <td>コメント数:<%=book.book_comments.count %></td>
           </tr>
         <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

bookers2/app/views/books/show.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
   <%= render 'books/sidebar', book: @book_new, user: @user %>
    <div class="col-md-8 offset-md-1">
      <h2>Book detail</h2>
      <table class="table">
        <tbody>
           <tr>
             <td>
               <%= link_to user_path(@book.user.id) do %>
                 <%= attachment_image_tag @book.user, :profile_image,  fallback: "no_image.jpg", class:"mt-3 rounded-circle", size: "40x40" %>
                 <br><%= @book.user.name %></br>
               <% end %>
             </td>
             <td>
               <%= link_to book_path(@book.id) do %>
                 <%= @book.title %>
               <% end %>
             </td>
             <td><%= @book.body %></td>
             <td id="book_<%= @book.id %>">
               <%= render 'favorites/list', book: @book %>
             </td>
             <td>
               コメント数:<%=@book.book_comments.count %>
             </td>
             <td>
               <% if @user.id == current_user.id %>
               <p><%= link_to "Edit", edit_book_path(@book), class: 'btn btn-sm btn-success' %></p>
               <% end %>
             </td>
             <td>
               <% if @user.id == current_user.id %>
               <p><%= link_to "Destroy", book_path(@book), method: :delete,"data-confirm" => "本当に消しますか?", class: 'btn btn-sm btn-danger' %></p>
               <% end %>
             </td>
           </tr>
        </tbody>
      </table>
      <div class="row">
          <div id="comments_area">
                 <%= render 'book_comments/index', book: @book %>
          </div>
     </div>
     <div class="form-group">
     <div class="error">
         <%= render 'book_comments/error_message', book_comment: @book_comment %>
     </div>
       <%= render partial: 'book_comments/form', locals: { book: @book, book_comment: @book_comment } %>
     </div>
    </div>
  </div>
</div>