bookers2/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users
  root to: 'homes#top'
  get "/home/about" =>"homes#about"

  get 'search' => 'searches#search'

  resources :books  do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end

  resources :users, only: [:index, :show, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end



end

bookers2/app/controllers/searches_controller.rb
class SearchesController < ApplicationController

  def search
    @range = params[:range]
    search = params[:search]
    @word = params[:word]
    if @range == "1"
      @user = User.search(search, @word)
    else
      @book = Book.search(search, @word)
    end
  end


end

bookers2/app/helpers/searches_helper.rb
module SearchesHelper
end

bookers2/app/views/searches/search.html.erb
<% if @range == "1" %>
   <h2>Users search for "<%= @word %>"</h2>
   <% if @user.exists? %>
     <table class="table">
       <thead>
         <tr>
           <th>image</th>
           <th>name</th>
           <th></th>
           <th></th>
           <th></th>
           <th></th>
         </tr>
       </thead>
       <tbody>
         <% @user.each do |user| %>
           <tr>
             <td>
               <a><%= attachment_image_tag user, :profile_image,  fallback: "no_image.jpg", class:"mt-3 rounded-circle", size: "40x40" %></a>
             </td>
             <td><%= user.name %></td>
             <td>フォロー数: <%= user.followings.count %></td>
             <td>フォロワー数: <%= user.followers.count %></td>
             <td>
               <% if user != current_user %>
                 <% if current_user.following?(user) %>
                   <%= link_to 'フォロー外す', user_relationships_path(user.id), method: :delete %>
                 <% else %>
                   <%= link_to 'フォローする', user_relationships_path(user.id), method: :post %>
                 <% end %>
               <% end %>
             </td>
             <td><%= link_to "Show", user_path(user) %></td>
           </tr>
         <% end %>
       </tbody>
     </table>
   <% else %>
     <p>No Users</p>
   <% end %>
<% else %>
   <h2>Books search for "<%= @word %> "</h2>
   <% if @book.exists? %>
     <table class="table">
       <thead>
         <tr>
           <th></th>
           <th>Title</th>
           <th>Opinion</th>
         </tr>
       </thead>
       <tbody>
         <% @book.each do |book| %>
           <tr>
             <td>
               <%= link_to user_path(book.user.id) do %>
                 <%= attachment_image_tag book.user, :profile_image,  fallback: "no_image.jpg", class:"mt-3 rounded-circle", size: "40x40" %>
               <% end %>
             </td>
             <td>
               <%= link_to book_path(book.id) do %>
                 <%= book.title %>
               <% end %>
             </td>
             <td><%= book.body %></td>
           </tr>
         <% end %>
       </tbody>
     </table>
   <% else %>
     <p>No Books</p>
   <% end %>
<% end %>